#!/bin/sh

RSYNC=/usr/bin/rsync
MAILER=/usr/bin/Mail
RM=/bin/rm
SCP=/usr/bin/scp

MAIL_LIST='support@xxx.com,marcel@xxx.com'
KEY_FILE=/root/root-rsync-key

# --archive = -a = -rlptgoD = default
MODIFIED_ARCHIVE=rltgoDz
RSYNC_PARAMS="-$MODIFIED_ARCHIVE --numeric-ids --recursive --update"
#BACKUP_SERVER=192.168.55.71
BACKUP_SERVER=xx.xx.xx.xx
BACKUP_USER=root
BACKUP_TARGET=/array/backups/websites

BACKUP_SRC=/home/foreclosures/www/
$RSYNC $RSYNC_PARAMS --rsh="ssh -i $KEY_FILE" $BACKUP_SRC $BACKUP_USER@$BACKUP_SERVER:$BACKUP_TARGET/xxx.xxx.com/www 2>/tmp/$$_rsync_errs
$SCP -i $KEY_FILE /home/foreclosures/indexer.conf $BACKUP_USER@$BACKUP_SERVER:$BACKUP_TARGET/xxx.xxx.com/ 2>>/tmp/$$_rsync_errs

BACKUP_SRC=/home/foreclosures/devel/
$RSYNC $RSYNC_PARAMS --rsh="ssh -i $KEY_FILE" $BACKUP_SRC $BACKUP_USER@$BACKUP_SERVER:$BACKUP_TARGET/xxx.xxx.com/devel 2>>/tmp/$$_rsync_errs

BACKUP_SRC=/home/foreclosuresinar/www/
$RSYNC $RSYNC_PARAMS --rsh="ssh -i $KEY_FILE" $BACKUP_SRC $BACKUP_USER@$BACKUP_SERVER:$BACKUP_TARGET/xxx.com/www 2>>/tmp/$$_rsync_errs

if [ -s /tmp/$$_rsync_errs ] ; then
   $MAILER -s 'forc6::Backup_websites : Rsync problems' $MAIL_LIST </tmp/$$_rsync_errs
else
   echo ' ' | $MAILER -s 'forc6::Backup_websites : successful' $MAIL_LIST
fi
$RM -f /tmp/$$_rsync_errs
